#pragma once
#include <stdint.h>

/* Autogenerated: axis-wise z-score on raw Ax,Ay,Az */
static const float AXIS_MEAN[3] = { -2.13214795, 1057.5138, -58.2942571 };
static const float AXIS_STD[3]  = { 176.231162, 277.850411, 233.24407 };
